/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "bruch_tests.ts" instead.
 */

#include <check.h>

#line 1 "bruch_tests.ts"
#include "bruch.h"

// checkmk bruch_tests.ts > bruch_tests.c
// gcc bruch.c bruch_tests.c -o tests -Wall -lm -lpthread -lrt -lcheck -lsubunit -std=c99 -g -fprofile-arcs -ftest-coverage

START_TEST(product_positive)
{
#line 7
    bruch a = { .nenner = 10, .zaehler = 5};
    bruch b = { .nenner = 2, .zaehler = 3};
    bruch c = product(a, b);
    ck_assert_int_eq(c.nenner, a.nenner*b.nenner);
    ck_assert_int_eq(c.zaehler, a.zaehler*b.zaehler);

}
END_TEST

START_TEST(product_negative)
{
#line 14
    bruch a = { .nenner = 10, .zaehler = 5};
    bruch b = { .nenner = -2, .zaehler = 3};
    bruch c = product(a, b);
    ck_assert_int_eq(c.nenner, a.nenner*b.nenner);
    ck_assert_int_eq(c.zaehler, a.zaehler*b.zaehler);

}
END_TEST

START_TEST(product_zero)
{
#line 21
    bruch a = { .nenner = 0, .zaehler = 5};
    bruch b = { .nenner = -2, .zaehler = 3};
    bruch c = product(a, b);
    ck_assert_int_eq(c.nenner, a.nenner*b.nenner);
    ck_assert_int_eq(c.zaehler, a.zaehler*b.zaehler);

}
END_TEST

START_TEST(change_nenner)
{
#line 28
    bruch a = { .nenner = 0, .zaehler = 5};
    set_nenner(&a, 5);
    ck_assert_int_eq(a.nenner, 5);
   
}
END_TEST

START_TEST(do_not_divide_through_zero)
{
#line 33
    bruch a = { .nenner = 0, .zaehler = 5};
    set_nenner(&a, 0);
    ck_assert_int_ne(a.nenner, 0);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, product_positive);
    tcase_add_test(tc1_1, product_negative);
    tcase_add_test(tc1_1, product_zero);
    tcase_add_test(tc1_1, change_nenner);
    tcase_add_test(tc1_1, do_not_divide_through_zero);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
