/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "dyn_array_tests.ts" instead.
 */

#include <check.h>

#line 1 "dyn_array_tests.ts"
#include "dyn_array.h"

// checkmk dyn_array_tests.ts > dyn_array_tests.c
// gcc dyn_array.c dyn_array_tests.c -o tests -Wall -lsubunit -lm -lpthread -lrt -lcheck -std=c99 -g -fprofile-arcs -ftest-coverage


START_TEST(check_create)
{
#line 8
    dyn_array *testarray = create();
    ck_assert_int_eq(testarray->fill_level, 0);
    ck_assert_int_eq(testarray->length, 1);


}
END_TEST

START_TEST(add_first_element)
{
#line 14
    dyn_array *testarray = create();
    add_last(testarray, "Erstes");
    ck_assert_int_eq(testarray->fill_level, 1);
    ck_assert_int_eq(testarray->length, 1);
    ck_assert_str_eq(testarray->strings[0], "Erstes");


}
END_TEST

START_TEST(double_size)
{
#line 22
    dyn_array *testarray = create();
    double_array(testarray);
    ck_assert_int_eq(testarray->fill_level, 0);
    ck_assert_int_eq(testarray->length, 2);
    double_array(testarray);
    ck_assert_int_eq(testarray->fill_level, 0);
    ck_assert_int_eq(testarray->length, 4);


}
END_TEST

START_TEST(add_more_elements)
{
#line 32
    dyn_array *testarray = create();
    add_last(testarray, "Erstes");
    add_last(testarray, "Zweites");
    ck_assert_int_eq(testarray->fill_level, 2);
    ck_assert_int_eq(testarray->length, 2);
    add_last(testarray, "Drittes");
    ck_assert_int_eq(testarray->fill_level, 3);
    ck_assert_int_eq(testarray->length, 4);
    add_last(testarray, "Viertes");
    ck_assert_int_eq(testarray->fill_level, 4);
    ck_assert_int_eq(testarray->length, 4);
    add_last(testarray, "Fünftes");
    ck_assert_int_eq(testarray->fill_level, 5);
    ck_assert_int_eq(testarray->length, 8);
    ck_assert_str_eq(testarray->strings[0], "Erstes");
    ck_assert_str_eq(testarray->strings[1], "Zweites");
    ck_assert_str_eq(testarray->strings[2], "Drittes");
    ck_assert_str_eq(testarray->strings[3], "Viertes");
    ck_assert_str_eq(testarray->strings[4], "Fünftes");
    
}
END_TEST

START_TEST(halve_size_empty_enough)
{
#line 53
    dyn_array *testarray = create();
    testarray->length = 16;
    halve_array(testarray);
    ck_assert_int_eq(testarray->fill_level, 0);
    ck_assert_int_eq(testarray->length, 8);
    halve_array(testarray);
    ck_assert_int_eq(testarray->fill_level, 0);
    ck_assert_int_eq(testarray->length, 4);
    testarray->fill_level = 2;
    halve_array(testarray);
    ck_assert_int_eq(testarray->fill_level, 2);
    ck_assert_int_eq(testarray->length, 2);


}
END_TEST

START_TEST(halve_size_not_empty_enough)
{
#line 68
    dyn_array *testarray = create();
    testarray->length = 16;
    testarray->fill_level = 9;
    halve_array(testarray);
    ck_assert_int_eq(testarray->fill_level, 9);
    ck_assert_int_eq(testarray->length, 16);

}
END_TEST

START_TEST(remove_last_element_no_size_changing)
{
#line 76
    dyn_array *testarray = create();
    add_last(testarray, "Erstes");
    add_last(testarray, "Zweites");
    add_last(testarray, "Drittes");
    add_last(testarray, "Viertes");
    remove_string(testarray, "Viertes");
    ck_assert_int_eq(testarray->fill_level, 3);
    ck_assert_int_eq(testarray->length, 4);
    ck_assert_str_eq(testarray->strings[0], "Erstes");
    ck_assert_str_eq(testarray->strings[1], "Zweites");
    ck_assert_str_eq(testarray->strings[2], "Drittes");


}
END_TEST

START_TEST(remove_last_element_with_size_changing)
{
#line 90
    dyn_array *testarray = create();
    add_last(testarray, "Erstes");
    add_last(testarray, "Zweites");
    add_last(testarray, "Drittes");
    add_last(testarray, "Viertes");
    add_last(testarray, "Fünftes");
    remove_string(testarray, "Fünftes");
    ck_assert_int_eq(testarray->fill_level, 4);
    ck_assert_int_eq(testarray->length, 4);
    ck_assert_str_eq(testarray->strings[0], "Erstes");
    ck_assert_str_eq(testarray->strings[1], "Zweites");
    ck_assert_str_eq(testarray->strings[2], "Drittes");
    ck_assert_str_eq(testarray->strings[3], "Viertes");


}
END_TEST

START_TEST(remove_only_element)
{
#line 106
    dyn_array *testarray = create();
    add_last(testarray, "Erstes");
    remove_string(testarray, "Erstes");
    ck_assert_int_eq(testarray->fill_level, 0);
    ck_assert_int_eq(testarray->length, 1);


}
END_TEST

START_TEST(remove_middle_element)
{
#line 114
    dyn_array *testarray = create();
    add_last(testarray, "Erstes");
    add_last(testarray, "Zweites");
    add_last(testarray, "Drittes");
    add_last(testarray, "Viertes");
    add_last(testarray, "Fünftes");
    remove_string(testarray, "Drittes");
    ck_assert_int_eq(testarray->fill_level, 4);
    ck_assert_int_eq(testarray->length, 4);
    ck_assert_str_eq(testarray->strings[0], "Erstes");
    ck_assert_str_eq(testarray->strings[1], "Zweites");
    ck_assert_str_eq(testarray->strings[2], "Viertes");
    ck_assert_str_eq(testarray->strings[3], "Fünftes");






    
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, check_create);
    tcase_add_test(tc1_1, add_first_element);
    tcase_add_test(tc1_1, double_size);
    tcase_add_test(tc1_1, add_more_elements);
    tcase_add_test(tc1_1, halve_size_empty_enough);
    tcase_add_test(tc1_1, halve_size_not_empty_enough);
    tcase_add_test(tc1_1, remove_last_element_no_size_changing);
    tcase_add_test(tc1_1, remove_last_element_with_size_changing);
    tcase_add_test(tc1_1, remove_only_element);
    tcase_add_test(tc1_1, remove_middle_element);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
